// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkOrderApplication.API.Data;

#nullable disable

namespace WorkOrderApplication.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251021120030_InitialCreateV04")]
    partial class InitialCreateV04
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkOrderApplication.API.Entities.CancelledProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CancelledDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("OrderProcessId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("OrderProcessId")
                        .IsUnique();

                    b.ToTable("CancelledProcesses", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.ConfirmProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConfirmedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderProcessId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderProcessId")
                        .IsUnique();

                    b.ToTable("ConfirmProcesses", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("RequestPerHour")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId", "MaterialNumber")
                        .IsUnique();

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.OrderGroupAMR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DestinationStation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DestinationStationId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceStation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SourceStationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderGroupId");

                    b.HasIndex("SourceStationId", "DestinationStationId")
                        .IsUnique();

                    b.ToTable("OrderGroupAMRs", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.OrderMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderProcessId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderQty")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrderProcessId");

                    b.ToTable("OrderMaterials", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.OrderMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Destination")
                        .HasColumnType("integer");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExecuteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExecutingIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MissionState")
                        .HasColumnType("integer");

                    b.Property<int>("OrderRecordByIdId")
                        .HasColumnType("integer");

                    b.Property<int>("ResultCode")
                        .HasColumnType("integer");

                    b.Property<string>("ResultStr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderRecordByIdId");

                    b.ToTable("OrderMissions");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.OrderProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("TimeToUse")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("WorkOrderId");

                    b.ToTable("OrderProcesses", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.OrderRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ExecutingIndex")
                        .HasColumnType("integer");

                    b.Property<string>("LastStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("OrderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("RawResponse")
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("OrderRecords", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.OrderRecordById", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DoneTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndStationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EndStationNo")
                        .HasColumnType("integer");

                    b.Property<string>("ExecuteVehicleKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExecuteVehicleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExecutingIndex")
                        .HasColumnType("integer");

                    b.Property<string>("FailReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderState")
                        .HasColumnType("integer");

                    b.Property<int>("OrderType")
                        .HasColumnType("integer");

                    b.Property<double>("Progress")
                        .HasColumnType("double precision");

                    b.Property<string>("RawResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartEndStationNameDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartStationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartStationNo")
                        .HasColumnType("integer");

                    b.Property<string>("TaskState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OrderRecordByIds");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.PreparingMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("PreparedQty")
                        .HasColumnType("integer");

                    b.Property<int>("PreparingProcessId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PreparingProcessId");

                    b.ToTable("PreparingMaterials", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.PreparingProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderProcessId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PreparedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PreparingByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortageReason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderProcessId")
                        .IsUnique();

                    b.HasIndex("PreparingByUserId");

                    b.ToTable("PreparingProcesses", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.ReceivedMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceivedProcessId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceivedQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ReceivedProcessId");

                    b.ToTable("ReceivedMaterials", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.ReceivedProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderProcessId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceivedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceivedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ShortageReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("OrderProcessId")
                        .IsUnique();

                    b.HasIndex("ReceivedByUserId");

                    b.ToTable("ReceivedProcesses", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.ReturnProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderProcessId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ReturnByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReturnDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("OrderProcessId")
                        .IsUnique();

                    b.HasIndex("ReturnByUserId");

                    b.ToTable("ReturnProcesses", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.ShipmentProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DestinationStation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DestinationStationId")
                        .HasColumnType("integer");

                    b.Property<string>("ExecuteVehicleKey")
                        .HasColumnType("text");

                    b.Property<string>("ExecuteVehicleName")
                        .HasColumnType("text");

                    b.Property<int?>("ExecutingIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSynced")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderProcessId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderState")
                        .HasColumnType("integer");

                    b.Property<double?>("Progress")
                        .HasColumnType("double precision");

                    b.Property<string>("SourceStation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceStationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderProcessId")
                        .IsUnique();

                    b.ToTable("ShipmentProcesses", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("WorkOrderNumber")
                        .IsUnique();

                    b.ToTable("WorkOrders", (string)null);
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.CancelledProcess", b =>
                {
                    b.HasOne("WorkOrderApplication.API.Entities.User", "CancelledBy")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WorkOrderApplication.API.Entities.OrderProcess", "OrderProcess")
                        .WithOne("CancelledProcess")
                        .HasForeignKey("WorkOrderApplication.API.Entities.CancelledProcess", "OrderProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CancelledBy");

                    b.Navigation("OrderProcess");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.ConfirmProcess", b =>
                {
                    b.HasOne("WorkOrderApplication.API.Entities.OrderProcess", "OrderProcess")
                        .WithOne("ConfirmProcess")
                        .HasForeignKey("WorkOrderApplication.API.Entities.ConfirmProcess", "OrderProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderProcess");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.Material", b =>
                {
                    b.HasOne("WorkOrderApplication.API.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Materials")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.OrderMaterial", b =>
                {
                    b.HasOne("WorkOrderApplication.API.Entities.Material", "Material")
                        .WithMany("OrderMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkOrderApplication.API.Entities.OrderProcess", "OrderProcess")
                        .WithMany("OrderMaterials")
                        .HasForeignKey("OrderProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("OrderProcess");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.OrderMission", b =>
                {
                    b.HasOne("WorkOrderApplication.API.Entities.OrderRecordById", "OrderRecord")
                        .WithMany("Missions")
                        .HasForeignKey("OrderRecordByIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderRecord");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.OrderProcess", b =>
                {
                    b.HasOne("WorkOrderApplication.API.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkOrderApplication.API.Entities.WorkOrder", "WorkOrder")
                        .WithMany("OrderProcesses")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.PreparingMaterial", b =>
                {
                    b.HasOne("WorkOrderApplication.API.Entities.Material", "Material")
                        .WithMany("PreparingMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkOrderApplication.API.Entities.PreparingProcess", "PreparingProcess")
                        .WithMany("PreparingMaterials")
                        .HasForeignKey("PreparingProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("PreparingProcess");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.PreparingProcess", b =>
                {
                    b.HasOne("WorkOrderApplication.API.Entities.OrderProcess", "OrderProcess")
                        .WithOne("PreparingProcess")
                        .HasForeignKey("WorkOrderApplication.API.Entities.PreparingProcess", "OrderProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkOrderApplication.API.Entities.User", "PreparingBy")
                        .WithMany()
                        .HasForeignKey("PreparingByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderProcess");

                    b.Navigation("PreparingBy");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.ReceivedMaterial", b =>
                {
                    b.HasOne("WorkOrderApplication.API.Entities.Material", "Material")
                        .WithMany("ReceivedMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkOrderApplication.API.Entities.ReceivedProcess", "ReceivedProcess")
                        .WithMany("ReceivedMaterials")
                        .HasForeignKey("ReceivedProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("ReceivedProcess");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.ReceivedProcess", b =>
                {
                    b.HasOne("WorkOrderApplication.API.Entities.OrderProcess", "OrderProcess")
                        .WithOne("ReceiveProcess")
                        .HasForeignKey("WorkOrderApplication.API.Entities.ReceivedProcess", "OrderProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkOrderApplication.API.Entities.User", "ReceivedBy")
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderProcess");

                    b.Navigation("ReceivedBy");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.ReturnProcess", b =>
                {
                    b.HasOne("WorkOrderApplication.API.Entities.OrderProcess", "OrderProcess")
                        .WithOne("ReturnProcess")
                        .HasForeignKey("WorkOrderApplication.API.Entities.ReturnProcess", "OrderProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkOrderApplication.API.Entities.User", "ReturnByUser")
                        .WithMany()
                        .HasForeignKey("ReturnByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderProcess");

                    b.Navigation("ReturnByUser");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.ShipmentProcess", b =>
                {
                    b.HasOne("WorkOrderApplication.API.Entities.OrderProcess", "OrderProcess")
                        .WithOne("ShipmentProcess")
                        .HasForeignKey("WorkOrderApplication.API.Entities.ShipmentProcess", "OrderProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderProcess");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.WorkOrder", b =>
                {
                    b.HasOne("WorkOrderApplication.API.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkOrderApplication.API.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.Material", b =>
                {
                    b.Navigation("OrderMaterials");

                    b.Navigation("PreparingMaterials");

                    b.Navigation("ReceivedMaterials");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.OrderProcess", b =>
                {
                    b.Navigation("CancelledProcess");

                    b.Navigation("ConfirmProcess");

                    b.Navigation("OrderMaterials");

                    b.Navigation("PreparingProcess");

                    b.Navigation("ReceiveProcess");

                    b.Navigation("ReturnProcess");

                    b.Navigation("ShipmentProcess");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.OrderRecordById", b =>
                {
                    b.Navigation("Missions");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.PreparingProcess", b =>
                {
                    b.Navigation("PreparingMaterials");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.ReceivedProcess", b =>
                {
                    b.Navigation("ReceivedMaterials");
                });

            modelBuilder.Entity("WorkOrderApplication.API.Entities.WorkOrder", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("OrderProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
